const slides=[
    new Slide('Narodziny Innowacji','W pierwszej połowie XIX wieku świat znajdował się na progu <span class="unique">rewolucji komunikacyjnej</span>. <span class="author">Samuel Morse</span>, artysta malarz i wynalazca, doznał tragicznego wydarzenia, które miało ogromny wpływ na jego przyszłe dokonania. W 1825 roku Morse otrzymał wiadomość o <span class="unique">śmiertelnej chorobie swojej żony</span> zbyt późno, aby zdążyć do niej przed jej śmiercią. Zrozpaczony tym, jak powolne były ówczesne metody komunikacji, postanowił poświęcić się poszukiwaniu szybszych i bardziej efektywnych sposobów przekazywania informacji.'),

    new Slide('<span class="headline">Wynalezienie Telegrafu</span>',`Inspiracja do stworzenia telegrafu pojawiła się podczas podróży morskiej do Europy, gdzie Morse zainteresował się <span class="unique">elektromagnetyzmem</span>. W 1832 roku, podczas powrotu do Stanów Zjednoczonych, wpadł na pomysł telegrafu elektrycznego. Z pomocą współpracowników, takich jak <span class="author">Alfred Vail</span>, udało mu się skonstruować działający prototyp. Telegraf Morse'a działał na zasadzie przesyłania sygnałów elektrycznych przez druty, które były odbierane i interpretowane przez urządzenie końcowe.`),

    new Slide(` <span class="headline">Powstanie Kodu Morse'a</span>`,`Jednakże sam telegraf nie byłby użyteczny bez odpowiedniego systemu kodowania informacji. Tutaj pojawia się jeden z największych wynalazków Morse'a - <span class="unique">kod Morse'a, stworzony w 1837 roku</span>. Kod ten opierał się na prostym systemie <span class="unique">kropek</span> i <span class="unique">kresek</span> (sygnałów krótkich i długich), które mogły reprezentować litery alfabetu, cyfry i znaki interpunkcyjne. Morse opracował ten kod, aby przekazywać wiadomości w sposób <span class="unique">szybki i jednoznaczny</span>, umożliwiając niemal natychmiastową komunikację na duże odległości.`),

    new Slide(`<span class="headline">Kod Morse'a w Praktyce</span>`,`<span class="unique">Pierwsza wiadomość</span> telegraficzna została przesłana przez Morse'a <span class="unique">24 maja 1844 roku</span>, z Waszyngtonu do Baltimore. Brzmiała ona: <span class="unique">"What hath God wrought?" (Co Bóg uczynił?)</span>. Ten historyczny przekaz oznaczał początek nowej ery komunikacji. Wkrótce sieci telegraficzne zaczęły rozprzestrzeniać się po całych Stanach Zjednoczonych i Europie, rewolucjonizując sposób, w jaki ludzie komunikowali się na dużych odległościach.`),

    new Slide(`<span class="headline">Zastosowania Kodu Morse'a</span>`,`Kod Morse'a znalazł szerokie zastosowanie w różnych dziedzinach. <span class="unique">Był kluczowy w komunikacji kolejowej, wojskowej oraz morskiej. </span>Podczas obu wojen światowych kod Morse'a był nieocenionym narzędziem w przekazywaniu <span class="unique">tajnych i pilnych informacji. </span> Nawet dziś, mimo rozwoju nowoczesnych technologii, kod Morse'a pozostaje ważnym środkiem komunikacji w sytuacjach awaryjnych i w środowiskach, gdzie tradycyjne metody są niedostępne.`),

    new Slide(`<span class="headline">Dziedzictwo Morse'a</span>`,`  <span class="author">Samuel Morse</span> zrewolucjonizował komunikację, przyczyniając się do powstania globalnej sieci telegraficznej. Jego wynalazek nie tylko przyspieszył tempo przekazywania informacji, ale także zbliżył do siebie ludzi na całym świecie. Kod Morse'a, pomimo upływu lat, pozostaje symbolem ludzkiej innowacyjności i dążenia do przełamywania barier.`)
];

const slider=new Slider('.sliderDiv b','.slide p','.nextSlide',slides);
slider.changeSlide('activeSlide')